### ISSUE TITLE
Error de despliegue

### ISSUE THREAD

**Issue by copex91** [egc-tests-grafica/agora-dev-box#1]
Al intentar desplegar la máquina de desarrollo en una instalación limpia de Ubuntu 16.04, se genera el error que se muestra en la imagen adjunta durante la ejecución del comando "vagrant provisioning".

![photo_2017-01-27_00-47-13](https://cloud.githubusercontent.com/assets/22837050/22355420/c486afc2-e42a-11e6-9311-aedd237281f5.jpg)

**Comment by octomonoli1** [comment]
Obtengo exactamente el mismo error en mi maquina con ubunto 16.04

**Comment by clavegber** [comment]
La incidencia está siendo investigada en estos momentos.

**Comment by clavegber** [comment]
Al ejecutar el comando vagrant provision para el Auth1 obtengo el mismo error pero en mi caso existe una leve diferencia. 

`TASK [Packages, upgrade postgresql db to 9.4] **********************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "cd && /usr/lib/postgresql/9.4/bin/pg_upgrade -b /usr/lib/postgresql/9.3/bin -B /usr/lib/postgresql/9.4/bin -d /etc/postgresql/9.3/main -D /etc/postgresql/9.4/main", "delta": "0:00:00.008623", "end": "2017-01-28 10:43:42.657242", "failed": true, "rc": 1, "start": "2017-01-28 10:43:42.648619", "stderr": "", "stdout": "Finding the real data directory for the new cluster         ok\n\ncheck for \"/usr/lib/postgresql/9.3/bin\" failed: No such file or directory\n\nFailure, exiting", "stdout_lines": ["Finding the real data directory for the new cluster         ok", "", "check for \"/usr/lib/postgresql/9.3/bin\" failed: No such file or directory", "", "Failure, exiting"], "warnings": []}
`

Como podemos ver, comparando ambos fallos, al principio de la traza del error vemos que para el compañero tenemos un "changed : false" mientras que en mi caso obtengo un "changed:true". 

He investigado sobre el error y una de las soluciones que se proponen es actualizar los paquetes postgresql, que es lo que nos da el error. Nuestro sistema tiene instalada la versión 9.5, y al intentar instalar la 9.2 y 9.4 nos da un fallo al encontrar los clusters. Por otra parte, al intentar actualizar las versiones seguimos obteniendo el mismo error por lo que seguimos sin poder ejecutar el comando "vagrant provision" con resultados satisfactorios.

**Comment by octomonoli1** [comment]
Ante los problemos que hemos estado teniendo con esto, para la mejora intentaremos realizar de nuevo un despliegue del entorno de desarrollo, siguiendo paso a paso, todo el manual ofrecido por agora-voting. En caso que sigamos con los errores y problemas, desarrollaremos los tests preparados para el entorno de producción.

**Comment by danpingue** [comment]
Sigo obteniendo el mismo error incluso reinstalando Ubuntu en la versión 14.04.

**Comment by octomonoli1** [comment]
Sigue trabajando sobre el entorno de producción, para que por lo menos podamos desarrollar los tests

**Comment by octomonoli1** [comment]
Estamos sin tiempo para solucionar esta issue. Tendremos que trabajar definitivamente con el enorno de producción.
