### ISSUE TITLE
Error de redirección en la página

### ISSUE THREAD

**Issue by clavegber** [egc-tests-grafica/agora-dev-box#10]
He ido a continuar con la realización de los tests sobre la página en producción  [Agora Voting](https://agoravoting.com/)  y al pulsar el botón de "Entra" para realizar el login me redirige a la página de contacto [Contacto](https://nvotes.com/contact/) en vez de a la página correspondiente para loguearme.

**Comment by octomonoli1** [comment]
Este problma debemos hacerlo llegar a ellos, le voy a dejar una issue, para ver si solucionan pronto esto, en caso que mañana no este contestada, les hablo por el chat

**Comment by octomonoli1** [comment]
@clavegber  Puedes continuar haciendo el test, utilizando la web de login, la cuál ya conocemos de los anteriores tests. https://go.nvotes.com/admin/login

**Comment by octomonoli1** [comment]
No he obtenido respuestas de parte de ellos, aunque esto no es bloqueante, puesto que ya conocemos la URL, seguimos con los test...
