### ISSUE TITLE
Test crear tweet

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#11]
Como añadido, vamos a crear un test para publicar el resultado de una votación. 
Para ello:
 - Nos vamos a crear una cuenta en yopmail "Realmente nunca llega a crearse" 
 - Nos registramos en twitter utilizando el correo yopmail.
 - Una vez tengamos esta cuenta, la utilizaremos para crear la nueva tarea. Y entonces comprobaremos resultados.

**Comment by clavegber** [comment]
No me permite el registro en Twitter usando yopmail por lo que me he creado un correo de gmail para realizar el registro y posteriormente el test.

**Comment by octomonoli1** [comment]
@clavegber Pues créalo con una cuenta google nueva, para no usar una personal de ninguno de nosotros....

**Comment by clavegber** [comment]
Hecho!

![imagen](https://cloud.githubusercontent.com/assets/22832742/22522592/692df2e8-e8bc-11e6-8e42-eec4158ee20c.png)
