### ISSUE TITLE
Test del formulario de Contactar

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#12]
Como teníamos decidido, vamos a realizar el test a la vista de contactar. Para ello, @clavegber realizará la parte principal del test y @copex91 Realizará el script de configuración.
Seguiremos el mismo metodo de trabajo y gestión que hemos seguido hasta ahora.

Se crearán las mejoras en la rama de desarrollo y yo me encargaré de unirlo a la master

**Comment by octomonoli1** [comment]
Confirmarme cuando vayas obteniendo resultados.

**Comment by clavegber** [comment]
Oído!

**Comment by octomonoli1** [comment]
No olvideis rellenar vuestro propio diario en la wiki

**Comment by octomonoli1** [comment]
Cuando la tarea este lista, por favor, subidme aquí un pantallazo como prueba del éxito en el que, a poder ser, aparezca, el success en la consola y el navegador con los resultados.

**Comment by copex91** [comment]
Archivo de configuración creado y subido correctamente a la rama de desarrollo.

**Comment by octomonoli1** [comment]
Ahora, @clavegber debe descargar el archivo de configuración y lanzar el script. Una vez esté listo, me lo indicáis por aquí y uno ambas ramas

**Comment by clavegber** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22832742/22541190/230887ba-e925-11e6-9857-493f348b8eeb.png)

Funcionando, procedo a subirlo a la rama de desarrollo

**Comment by octomonoli1** [comment]
Perfecto, cierro esta tarea
