### ISSUE TITLE
Diario de Defensa

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#13]
Usando el mismo diario entregado,  @danpingue debes introducir el trabajo de cada miembro en el día de hoy. Recuerda que hemos empezado a las 8:30 y debemos haber acabado a las 9:00

**Comment by danpingue** [comment]
[Diario de Grupo (Milestone 5).docx](https://github.com/egc-tests-grafica/agora-dev-box/files/747094/Diario.de.Grupo.Milestone.5.docx)
Realizado el diario de grupo del milestone 5.

**Comment by octomonoli1** [comment]
PErfecto, cierro esta también
