### ISSUE TITLE
Documento de Mejora

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#2]
Realizar un documento de mejora que recoja todos los aspectos

**Comment by octomonoli1** [comment]
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/737722/Manual.de.Mejora.docx)

**Comment by clavegber** [comment]
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/737750/Manual.de.Mejora.docx)

Te adjunto el documento con algunos errores señalados y alguna propuesta de mejora de la documentación. 

Por otro lado, añadir a eso las siguientes instrucciones por parte del profesor que no se han tenido en cuenta:

- En la portada poner nombres y apellidos de cada componente, grupo al que pertenecen (1 o 2, mañana o tarde), curso académico, nombre del proyecto (deliberaciones, almacenamiento,...) e ID de Opera.

- Siempre enumerar las secciones y subsecciones

**Comment by octomonoli1** [comment]
Gracias @clavegber paso el doc corregido
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/737755/Manual.de.Mejora.docx)

**Comment by octomonoli1** [comment]
Nueva Versión del Documento de Mejora 1.0.2
[Manual.de.Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/739423/Manual.de.Mejora.docx)

**Comment by danpingue** [comment]
**Posibles errores del documento:**
- En la portada aparece como número de grupo el 15.
- En el apartado Introducción aparece la palabra cuso en vez de curso.

**Mejoras del documento:**
- Hay distintos tipos de letras en el documento.
- Creo que estaría mejor si se pusiera el texto justificado.

**Comment by octomonoli1** [comment]
Finalizada la documentación de mejora.
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/745734/Manual.de.Mejora.docx)

**Comment by octomonoli1** [comment]
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/745899/Manual.de.Mejora.docx)

**Comment by octomonoli1** [comment]
[Manual de Mejora.docx](https://github.com/egc-tests-grafica/agora-dev-box/files/746357/Manual.de.Mejora.docx)
