### ISSUE TITLE
Diario de grupo

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#3]
Realizar un documento diario de grupo en el que aparezcan las fechas y duraciones de cada tarea desarrollada en cada iteración de equipo. Debe aparecer los miembros que realizan cada tarea.

**Comment by danpingue** [comment]
Se ha modificado la estructura del documento al cuál se le ha añadido portada, historial de versiones y el listado de participantes en la mejora.

**Comment by octomonoli1** [comment]
Perfecto, la lista de diarios de cada participante esta en la wiki de este repo. De ahi se puede ir sacando la informacion diaria para crear el "diario completo final"

**Comment by octomonoli1** [comment]
Del milestone de documentación solo queda esto. Una vez lo finalices, puedes cerrar tu mismo esta tarea para completarlo

**Comment by danpingue** [comment]
[Diario de Grupo.pdf](https://github.com/egc-tests-grafica/agora-dev-box/files/746367/Diario.de.Grupo.pdf)
Adjunto el diario de grupo y cierro esta tarea tal y como me has indicado @octomonoli1

**Comment by octomonoli1** [comment]
Perfecto! lo preparo para la entrega
