### ISSUE TITLE
Test Crear Votación

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#5]
Este tes debe realizar los siguientes pasos
- Inicio de sesión
- Crear votación
- Crear Opciones
- Cerrar Sesión

**Comment by octomonoli1** [comment]
@clavegber Una vez realices el test, necesito unos screenshots del resultado por aquí para añadirlos al manual

**Comment by clavegber** [comment]
En proceso

**Comment by octomonoli1** [comment]
@clavegber En que estado se encuentra esto? Una vez este completo cierra esta tarea pls

**Comment by clavegber** [comment]
Sigue en proceso, funcionando ya pero queda añadir mejoras al test y añadir el cerrar sesión.

**Comment by clavegber** [comment]
![crear encuesta success](https://cloud.githubusercontent.com/assets/22832742/22517842/cc4820c2-e8aa-11e6-9d28-f95259d083e2.jpg)

**Comment by octomonoli1** [comment]
Buen trabajo @clavegber. He comprobado resultados y procedo a cerrar esta tarea.
