### ISSUE TITLE
Test Votar

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#6]
Este test debe contemplar lo siguieente:
- Usar la URL generada por AV para votar
- Realizar el voto
- Asegurarse que dicho voto se ha realizado

**Comment by octomonoli1** [comment]
@copex91 Una vez realices el test, necesito unos screenshots del resultado por aquí para añadirlos al manual

**Comment by octomonoli1** [comment]
Para votar se debe generar la url de voto y enviarla al correo del usuario que vaya a votar. Debemos estar registrados en el portal y usar esa URL para el test

**Comment by octomonoli1** [comment]
@copex91 Necesito información sobre este test. ¿En que estado está? Una vez finalices con el cierralo plss

**Comment by octomonoli1** [comment]
@copex91 EHHHHHHHHHHHHHHHHHHHH

**Comment by octomonoli1** [comment]
@copex91 Las taja vinagreeeeeeeeeeeeeehhh

**Comment by copex91** [comment]
El test está creado y en la rama de desarrollo, con una mejora incluida para comprobar la validez del hash del voto devuelto cuando se finaliza la votación.

**Comment by octomonoli1** [comment]
Perfecto, incluiré esa mejora de comprobación en las mejoras del proyecto. Gracias! Cierro Tarea que ya no queda nada!
