### ISSUE TITLE
Test Cerrar votación

### ISSUE THREAD

**Issue by octomonoli1** [egc-tests-grafica/agora-dev-box#7]
Test para cerrar la votación (Ya votada)
- Iniciar sesión en la aplicación
- Seleccionar el voto que deseamos cerrar
- Cerrarlo pulsando el botón
- Asegurarse que esta Cerrado

**Comment by octomonoli1** [comment]
@danpingue Una vez realices el test, necesito unos screenshots del resultado por aquí para añadirlos al manual

**Comment by octomonoli1** [comment]
Recordar que para que el test se pueda cerrar y podamos comprobar los resultados, este test debe tener al menos un voto, es decir, hay que dejar preparado un voto ya con votos realizados, o ejecutar justo antes de este test, el test de votar.

**Comment by danpingue** [comment]
En proceso la realización del test requerido.

**Comment by danpingue** [comment]
He subido el test una vez que lo he vuelto a revisar. Queda pendiente de añadirle posibles mejoras.

**Comment by octomonoli1** [comment]
Necesito que me deis informacion sobre esto. Esta ya al 100%? Para cerrarlo

**Comment by danpingue** [comment]
Espero poder terminarlo hoy añadiéndole la mejora que crea oportuna. En cuanto esté listo te lo indicaré por aquí para que puedas comprobarlo @octomonoli1

**Comment by danpingue** [comment]
Dado que el cerrar encuesta sólo depende del botón de cerrar encuesta y el de confirmar encuesta, no he encontrado nada que pueda hacer que se mejore este test. 

Le he añadido comentarios como mejora para una mejor descripción de cada paso.

Lo dejo pendiente de tu aprobación @octomonoli1 en la rama **desarrollo**.

**Comment by danpingue** [comment]
Te envío los resultados de ejecución del test:
- Resultado final de la web
![test correcto](https://cloud.githubusercontent.com/assets/22832260/22519770/f6169c60-e8b1-11e6-849a-ca3d4e36ba3f.png)

- Resultado final del test
![test ok](https://cloud.githubusercontent.com/assets/22832260/22519779/fd2bc7fa-e8b1-11e6-915f-6af3043b30fb.png)

**Comment by octomonoli1** [comment]
Perfecto, ya esta comprobado, he utilizado estos screenshots para el documento de mejora. Cierro esta tarea.
